opcodes = {
	'00':['BRK', '',     '7'],
	'01':['ORA', 'indX', '6'],
	'02':['STP', '',     '0'],
	'03':['SLO', 'indX', '8'],
	'04':['NOP', 'zp',   '3'],
	'05':['ORA', 'zp',   '3'],
	'06':['ASL', 'zp',   '5'],
	'07':['SLO', 'zp',   '5'],
	'08':['PHP', '',     '3'],
	'09':['ORA', 'imm',  '2'],
	'0a':['ASL', 'acc',  '2'],
	'0b':['AAC', 'imm',  '2'],
	'0c':['NOP', 'abs',  '4'],
	'0d':['ORA', 'abs',  '4'],
	'0e':['ASL', 'abs',  '6'],
	'0f':['SLO', 'abs',  '6'],

	'10':['BPL', 'imm',  '2+'],
	'11':['ORA', 'indY', '5+'],
	'12':['STP', '',     '0'],
	'13':['SLO', 'indY', '8'],
	'14':['NOP', 'zpX',  '4'],
	'15':['ORA', 'zpX',  '4'],
	'16':['ASL', 'zpX',  '6'],
	'17':['SLO', 'zpX',  '6'],
	'18':['CLC', '',     '2'],
	'19':['ORA', 'absY', '4+'],
	'1a':['NOP', '',     '2'],
	'1b':['SLO', 'absY', '7'],
	'1c':['NOP', 'absX', '4+'],
	'1d':['ORA', 'absX', '4+'],
	'1e':['ASL', 'absX', '7'],
	'1f':['SLO', 'absX', '7'],

	'20':['JSR', 'abs',  '6'],
	'21':['AND', 'indX', '6'],
	'22':['STP', '',     '0'],
	'23':['RLA', 'indX', '8'],
	'24':['BIT', 'zp',   '3'],
	'25':['AND', 'zp',   '3'],
	'26':['ROL', 'zp',   '5'],
	'27':['RLA', 'zp',   '5'],
	'28':['PLP', '',     '4'],
	'29':['AND', 'imm',  '2'],
	'2a':['ROL', 'acc',  '2'],
	'2b':['AAC', 'imm',  '2'],
	'2c':['BIT', 'abs',  '4'],
	'2d':['AND', 'abs',  '4'],
	'2e':['ROL', 'abs',  '6'],
	'2f':['RLA', 'abs',  '6'],

	'30':['BMI', 'imm',  '2+'],
	'31':['AND', 'indY', '5+'],
	'32':['STP', '',     '0'],
	'33':['RLA', 'indY', '8'],
	'34':['NOP', 'zpX',  '4'],
	'35':['AND', 'zpX',  '4'],
	'36':['ROL', 'zpX',  '6'],
	'37':['RLA', 'zpX',  '6'],
	'38':['SEC', '',     '2'],
	'39':['AND', 'absY', '4+'],
	'3a':['NOP', '',     '2'],
	'3b':['RLA', 'absY', '7'],
	'3c':['NOP', 'absX', '4+'],
	'3d':['AND', 'absX'],
	'3e':['ROL', 'absX', '7'],
	'3f':['RLA', 'absX', '7'],

	'40':['RTI', '',     '6'],
	'41':['EOR', 'indX', '6'],
	'42':['STP', '',     '0'],
	'43':['SRE', 'indX', '8'],
	'44':['NOP', 'zp',   '3'],
	'45':['EOR', 'zp',   '3'],
	'46':['LSR', 'zp',   '5'],
	'47':['SRE', 'zp',   '5'],
	'48':['PHA', '',     '3'],
	'49':['EOR', 'imm',  '2'],
	'4a':['LSR', 'acc',  '2'],
	'4b':['ASR', 'imm',  '2'],
	'4c':['JMP', 'abs',  '3'],
	'4d':['EOR', 'abs',  '4'],
	'4e':['LSR', 'abs',  '6'],
	'4f':['SRE', 'abs',  '6'],

	'50':['BVC', 'imm',  '2+'],
	'51':['EOR', 'indY', '5+'],
	'52':['STP', '',     '0'],
	'53':['SRE', 'indY', '8'],
	'54':['NOP', 'zpX',  '4'],
	'55':['EOR', 'zpX',  '4'],
	'56':['LSR', 'zpX',  '6'],
	'57':['SRE', 'zpX',  '6'],
	'58':['CLI', '',     '2'],
	'59':['EOR', 'absY', '4+'],
	'5a':['NOP', '',     '2'],
	'5b':['SRE', 'absY', '7'],
	'5c':['NOP', 'absX', '4+'],
	'5d':['EOR', 'absX', '4+'],
	'5e':['LSR', 'absX', '7'],
	'5f':['SRE', 'absX', '7'],

	'60':['RTS', '',     '6'],
	'61':['ADC', 'indX', '6'],
	'62':['STP', '',     '0'],
	'63':['RRA', 'indX', '8'],
	'64':['NOP', 'zp',   '3'],
	'65':['ADC', 'zp',   '3'],
	'66':['ROR', 'zp',   '5'],
	'67':['RRA', 'zp',   '5'],
	'68':['PLA', '',     '4'],
	'69':['ADC', 'imm',  '2'],
	'6a':['ROR', 'acc',  '2'],
	'6b':['ARR', 'imm',  '2'],
	'6c':['JMP', 'ind',  '5'],
	'6d':['ADC', 'abs',  '4'],
	'6e':['ROR', 'abs',  '6'],
	'6f':['RRA', 'abs',  '6'],

	'70':['BVS', 'imm',  '2+'],
	'71':['ADC', 'indY', '5+'],
	'72':['STP', '',     '0'],
	'73':['RRA', 'indY', '8'],
	'74':['NOP', 'zpX',  '4'],
	'75':['ADC', 'zpX',  '4'],
	'76':['ROR', 'zpX',  '6'],
	'77':['RRA', 'zpX',  '6'],
	'78':['SEI', '',     '2'],
	'79':['ADC', 'absY', '4+'],
	'7a':['NOP', '',     '2'],
	'7b':['RRA', 'absY', '7'],
	'7c':['NOP', 'absX', '4+'],
	'7d':['ADC', 'absX', '4+'],
	'7e':['ROR', 'absX', '7'],
	'7f':['RRA', 'absX', '7'],

	'80':['NOP', 'imm',  '2'],
	'81':['STA', 'indX', '6'],
	'82':['NOP', 'imm',  '2'],
	'83':['AAX', 'indX', '6'],
	'84':['STY', 'zp',   '3'],
	'85':['STA', 'zp',   '3'],
	'86':['STX', 'zp',   '3'],
	'87':['AAX', 'zp',   '3'],
	'88':['DEY', '',     '2'],
	'89':['NOP', 'imm',  '2'],
	'8a':['TXA', '',     '2'],
	'8b':['XAA', 'imm',  '2'],
	'8c':['STY', 'abs',  '4'],
	'8d':['STA', 'abs',  '4'],
	'8e':['STX', 'abs',  '4'],
	'8f':['AAX', 'abs',  '4'],

	'90':['BCC', 'imm',  '2+'],
	'91':['STA', 'indY', '6'],
	'92':['STP', '',     '0'],
	'93':['AXA', 'indY', '6'],
	'94':['STY', 'zpX',  '4'],
	'95':['STA', 'zpX',  '4'],
	'96':['STX', 'zpY',  '4'],
	'97':['AAX', 'zpY',  '4'],
	'98':['TYA', '',     '2'],
	'99':['STA', 'absY', '5'],
	'9a':['TXS', '',     '2'],
	'9b':['XAS', 'absY', '5'],
	'9c':['SYA', 'absX', '5'],
	'9d':['STA', 'absX', '5'],
	'9e':['SXA', 'absY', '5'],
	'9f':['AXA', 'absY', '5'],

	'a0':['LDY', 'imm',  '2'],
	'a1':['LDA', 'indX', '6'],
	'a2':['LDX', 'imm',  '2'],
	'a3':['LAX', 'indX', '6'],
	'a4':['LDY', 'zp',   '3'],
	'a5':['LDA', 'zp',   '3'],
	'a6':['LDX', 'zp',   '3'],
	'a7':['LAX', 'zp',   '3'],
	'a8':['TAY', '',     '2'],
	'a9':['LDA', 'imm',  '2'],
	'aa':['TAX', '',     '2'],
	'ab':['ATX', 'imm',  '2'],
	'ac':['LDY', 'abs',  '4'],
	'ad':['LDA', 'abs',  '4'],
	'ae':['LDX', 'abs',  '4'],
	'af':['LAX', 'abs',  '4'],

	'b0':['BCS', 'imm',  '2+'],
	'b1':['LDA', 'indY', '5+'],
	'b2':['STP', '',     '0'],
	'b3':['LAX', 'indY', '5+'],
	'b4':['LDY', 'zpX',  '4'],
	'b5':['LDA', 'zpX',  '4'],
	'b6':['LDX', 'zpY',  '4'],
	'b7':['LAX', 'zpY',  '4'],
	'b8':['CLV', '',     '2'],
	'b9':['LDA', 'absY', '4+'],
	'ba':['TSX', '',     '2'],
	'bb':['LAR', 'absY', '4+'],
	'bc':['LDY', 'absX', '4+'],
	'bd':['LDA', 'absX', '4+'],
	'be':['LDX', 'absY', '4+'],
	'bf':['LAX', 'absY', '4+'],

	'c0':['CPY', 'imm',  '2'],
	'c1':['CMP', 'indX', '6'],
	'c2':['NOP', 'imm',  '2'],
	'c3':['DCP', 'indX', '8'],
	'c4':['CPY', 'zp',   '3'],
	'c5':['CMP', 'zp',   '3'],
	'c6':['DEC', 'zp',   '5'],
	'c7':['DCP', 'zp',   '5'],
	'c8':['INY', '',     '2'],
	'c9':['CMP', 'imm',  '2'],
	'ca':['DEX', '',     '2'],
	'cb':['AXS', 'imm',  '2'],
	'cc':['CPY', 'abs',  '4'],
	'cd':['CMP', 'abs',  '4'],
	'ce':['DEC', 'abs',  '6'],
	'cf':['DCP', 'abs',  '6'],

	'd0':['BNE', 'imm',  '2+'],
	'd1':['CMP', 'indY', '5+'],
	'd2':['STP', '',     '0'],
	'd3':['DCP', 'indY', '8'],
	'd4':['NOP', 'zpX',  '4'],
	'd5':['CMP', 'zpX',  '4'],
	'd6':['DEC', 'zpX',  '6'],
	'd7':['DCP', 'zpX',  '6'],
	'd8':['CLD', '',     '2'],
	'd9':['CMP', 'absY', '4+'],
	'da':['NOP', '',     '2'],
	'db':['DCP', 'absY', '7'],
	'dc':['NOP', 'absX', '4+'],
	'dd':['CMP', 'absX', '4+'],
	'de':['DEC', 'absX', '7'],
	'df':['DCP', 'absX', '7'],

	'e0':['CPX', 'imm',  '2'],
	'e1':['SBC', 'indX', '6'],
	'e2':['NOP', 'imm',  '2'],
	'e3':['ISC', 'indX', '8'],
	'e4':['CPX', 'zp',   '2'],
	'e5':['SBC', 'zp',   '3'],
	'e6':['INC', 'zp',   '5'],
	'e7':['ISC', 'zp',   '5'],
	'e8':['INX', '',     '2'],
	'e9':['SBC', 'imm',  '2'],
	'ea':['NOP', '',     '2'],
	'eb':['SBC', 'imm',  '2'],
	'ec':['CPX', 'abs',  '3'],
	'ed':['SBC', 'abs',  '4'],
	'ee':['INC', 'abs',  '6'],
	'ef':['ISC', 'abs',  '6'],

	'f0':['BEQ', 'imm',  '2+'],
	'f1':['SBC', 'indY', '5+'],
	'f2':['STP', '',     '0'],
	'f3':['ISC', 'indY', '8'],
	'f4':['NOP', 'zpX',  '4'],
	'f5':['SBC', 'zpX',  '4'],
	'f6':['INC', 'zpX', '6'],
	'f7':['ISC', 'zpX',  '6'],
	'f8':['SED', '',     '2'],
	'f9':['SBC', 'absY', '4+'],
	'fa':['NOP', '',     '2'],
	'fb':['ISC', 'absY', '7'],
	'fc':['NOP', 'absX', '4+'],
	'fd':['SBC', 'absX', '4+'],
	'fe':['INC', 'absX', '7'],
	'ff':['ISC', 'absX', '7'],
}

bLen = {
	''    : 1,
	'acc' : 1,
	'imm' : 2,
	'zp'  : 2,
	'zpX' : 2,
	'zpY' : 2,
	'abs' : 3,
	'absX': 3,
	'absY': 3,
	'ind' : 3,
	'indX': 2,
	'indY': 2
}

# Implied: no operand
# Accumulator: no operan

# Immediate: Operand Value
# Zero Page: RAM[00 + Operand]
# Zero Page, X: RAM[00 + Operand + X]
# Zero Page, Y: RAM[00 + Operand + Y]
# Absolute: RAM[Operand]
# Absolute, X: RAM[Operand + X]
# Absolute, Y: RAM[Operand + Y]
# (Indirect, X): RAM[RAM[Operand + X]]
# (Indirect), Y: RAM[RAM[Operand] + Y]
